[package]
name = "fuzz"
version = "0.1.0"
edition = "2024"

[dependencies]
afl = "*"
axum = "0.8.4"
bile = { path = ".." }
http = "1.3.1"
http-body-util = "0.1.3"
tokio = { version = "1.47.1", features = ["rt-multi-thread", "fs"] }
tower = "0.5.2"
